apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml
  - ingress.yml

images:
  - name: __WEB_APP_IMAGE__
    newName: ap-chuncheon-1.ocir.io/axaddw88ufgp/number-planet
    newTag: 0.0.4

commonLabels:
  app: number-planet
